### ISSUE TITLE
建议日历和THB日程关联同步

### ISSUE THREAD

**Issue by RingingVolcano** [Whuihuan/THBWiki-Ext#1]
希望能在日历中显示THB的新闻、活动和展会日程之类的
https://thwiki.cc/%E6%97%A5%E7%A8%8B%E8%A1%A8
https://thwiki.cc/%E6%96%B0%E9%97%BB

**Comment by Whuihuan** [comment]
由于THB接口限制，无法做到直接获取具体哪年哪月的数据，THB接口获取的数据属于从最新的大事记记录开始往前获取多少条，而不能获得哪年哪月的大事记。也就是说现在是2021年1月，假设前50条是2021年1月到2020年12月的数据，那我要获取2020年10月的数据得不断请求接口（50条、100条、150条....），直到找到2020年10月的数据为止，并且最大条数不能超过1000条。所以如果这个要做的话，可能只能做到最近几个月内的前50条大事记，因为我曾经测试过100条获取很慢。

**Comment by Whuihuan** [comment]
虽然有个方案能实现，但是上面说的问题仍然避免不了。所以可能只会显示未来以及到当月1号的日历。

**Comment by Whuihuan** [comment]
dev已更新

**Comment by RingingVolcano** [comment]
> dev已更新

好的 感谢了！
